<a href="https://colab.research.google.com/github/ji0-k/AI_26/blob/main/book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # 별칭쓰고

print(np.array([1,2,3]))

[1 2 3]


In [2]:
import numpy #별칭안쓰고
print(numpy.array([1,2,3]))

[1 2 3]


In [3]:
import numpy as np

arr_1 = np.array([1,2,3,4,5]) # 파이썬 리스트를 넘파일 배열로 변환
print(arr_1) #넘파이 배열 출력 , 출력에는 쉼표없음

[1 2 3 4 5]


In [7]:
arr_1 = np.array([1,2,3,4,5]*2) # 리스트 두번 출력
print(arr_1)
#[1 2 3 4 5 1 2 3 4 5]

[1 2 3 4 5 1 2 3 4 5]


In [9]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1*2) # 리스트 안의 각 요소에 2를곱하여 나옴
#[ 2  4  6  8 10]

[ 2  4  6  8 10]


In [11]:
# 2차원 배열 매트릭스, 행렬
import numpy as np

arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# 3차원 배열 큐브, 볼륨

import numpy as np

arr_3 = np.array([[[1,1,1],[1,1,1]],[[2,2,2],[2,2,2]],[[3,3,3],[3,3,3]]])
print(arr_3)

[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]]]


In [15]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1.dtype) #데이터타입 알려줘


int64


In [ ]:
# 부호가 있는
# 정수 int (-128~127)
# 정수 데이터 타입 코드 i,

#부호가 없는 (음양 부호 비트 없음 메모리 효율)
#없는 정수 데이터타입 unit (0~255까지 256개)
# ㅇ벗는 정수 데이터 타입코드 u

# 실수
# 데이터타입 float : 3.4*10^-38 부터 3.4*10^38 , 포함
# 데이터 타입 코드 f

# 논리형 데이터 타입 boolean : bool
# 논리형 데이터 타입 코드 ?

In [17]:
import numpy as np

ndarray_1 = np.array([1,2,3])
ndarray_2 = np.array([4,5,6])
list_1 =[1,2,3]
list_2 =[4,5,6]

print(ndarray_1 +ndarray_2) # 넘파이 배열 힙
print(list_1 + list_2)      # 리스트 배열 합 결과 다름

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [22]:
result_list = [x+y for x,y in zip (list_1, list_2)]
result_list2 = [x+y for x,y in zip (list_1, ndarray_1)]
print(result_list)
print(result_list2)

[5, 7, 9]
[np.int64(2), np.int64(4), np.int64(6)]


In [18]:
print(ndarray_1 *2) # 넘파이 배열 곱
print(list_1 *2)    # 리스트 배열 곱

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [23]:
print(ndarray_1)
print(ndarray_1.dtype)

[1 2 3]
int64


In [30]:
import numpy as np  # 넘파이 라이브러리를 불러옵니다.

# 리스트를 np.array()로 감싸서 넘파이 배열로 생성합니다.
ndarray_3 = np.array([1.2, 2.3, 3.4, 4.5, 5.6])

print(ndarray_3)        # 배열의 내용 출력
print(ndarray_3.dtype)  # 이제 정상적으로 float64(실수형) 데이터 타입이 출력됩니다.

[1.2 2.3 3.4 4.5 5.6]
float64


In [ ]:
# ndarray.shape : 배열의 축 수서대로 크기를 튜플로 반환 각 aixs의 크기
# ndarray.ndim : 차원의 개수 반환
# ndarray.dtype : 배열 요소의 데이터 타입 반호ㅑㅏㄴ
# ndarray